### ISSUE TITLE
1. Single Environment : Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'.

### ISSUE THREAD

**Issue by paulvelzeboer** [OutSystems/AzureARMTemplates#17]
Hello,

if i want to use the templates i get the following validation error:

Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'.

more details:

{
  "deploymentStatusCode": -1,
  "stage": 6,
  "expected": true,
  "error": {
    "message": "Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'."
  },
  "subscriptionId": "3d786556-eccc-4ad8-837f-a6ddd1d4e682",
  "resourceGroupName": "test",
  "resourceGroupLocation": "westeurope",
  "deploymentName": "Microsoft.Template-20200827143429",
  "details": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 26,
          "linePosition": 25,
          "path": "parameters.withPublicIp"
        }
      }
    ]
  }
}

**Comment by anabarata** [comment]
Hello @paulvelzeboer 

Can you please test your deployment again? The issue seems to be fixed now.

Thank you

**Comment by paulvelzeboer** [comment]
tested and problem solved!!
