### ISSUE TITLE
Resources (JSON)  not available anymore? 

### ISSUE THREAD

**Issue by pvdochtend** [OutSystems/AzureARMTemplates#6]
The links in the ReadMe are referencing a folder called resources but that folder isn't there anymore.

Example: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOutSystems%2FAzureARMTemplates%2Fmaster%2Fresources%2FvirtualNetworkVMSS.json
For Virtual Network.

Is that right?

The reason why I looked at this GitHub because the MarketPlace template is creating all environments and I only need three (Lifetime, Dev, Prod). No Test / Acceptance etc.

**Comment by pintonunes** [comment]
Yes, its a bug. They will be available soon again. We did a huge refactoring of the templates and forgot the VNET templates. 
Meanwhile you can deploy the VNET manually. Just make sure you select the SQL endpoint. You need at least 2 subnets. One for the VM and another for the appgw. 
But we will put those back very soon.

**Comment by pvdochtend** [comment]
I solved it by checking out an older version of the git and use the script (with some small changes) that was there. 
Works well. Keep up the good work with giving us the tools for automated deploys etc. 🤙🏻

**Comment by pauloalexcosta** [comment]
Hi @pvdochtend , I just "restored" the resources folder with the 3 VNet json files. The links on the read.me are now working again.

Thanks for the heads-up, this had completely escaped our sights when we did the merge from the refactor branch. 👍
