### ISSUE TITLE
Error provisioning Virtual Machine Extension OutSystemsProvisioning on single OutSystems environment template

### ISSUE THREAD

**Issue by jpb-teixeira** [OutSystems/AzureARMTemplates#7]
I'm facing some issues using environment.json template. The issue is regarding the installation/provisioning of the virtual machine extension "OutSystemsProvisioning".

I'm providing the error information on the image bellow:
![image](https://user-images.githubusercontent.com/46999210/62880447-4f192b80-bd25-11e9-8719-5242ce4fd1e2.png)

Have you ever face this kind of error? I've tried to deploy three times and it gaves me every time the same error.

Thanks!

**Comment by pintonunes** [comment]
Hi @jpb-teixeira,
That means that the provisioning script failed.
Can you check the logs in the failed VM in C:\Windows\Temp\OutSystems.Setuptools?

**Comment by mlenartowicz** [comment]
I've had the same issue, the logs said:

VERBOSE : 11:28:51.7971262 [Set-OSServerConfig]  [PROCESS]  Configuration Tool: Connection to the cache invalidation service failed: None of the specified endpoints were reachable. ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.

Somehow the RabitMQ wasn't configured properly, so I configured it manually according to https://success.outsystems.com/Support/Enterprise_Customers/Maintenance_and_Operations/Cache_Invalidation_in_OutSystems_11/RabbitMQ_management_and_troubleshooting

**Comment by pintonunes** [comment]
Yes.. From the log it is rabbitmq related and the issue is the password. 
We dont have any password check mechanism and we know that the deployment can fail if some non alphabetic characters are used.
